name 'Analytical Labs-jenkins'
version ''

author 'Tom Barber'
license ''
project_page 'https://github.com/OSBI/puppet-jenkins'
source 'git@github.com:OSBI/puppet-jenkins.git'
summary 'Basic Jenkins Module'
description ''
dependency 'Analytical Labs/apache', '==1.0'
dependency 'Analytical Labs/tomcat', '==1.0'
dependency 'Analytical Labs/java', '==1.0'
dependency 'Analytical Labs/git', '==1.0'
dependency 'Analytical Labs/subversion', '==1.0'
